Fix tests 1.0.0
php-rdkafka/php-rdkafka pull request #223
Opened 2019-05-10 01:44 UTC by Steveb-p

Will resolve #220 eventually.

Contains resolution for segfault issue as well.

2019-05-10 01:45 UTC, Steveb-p commented on tests/conf_callbacks_integration.phpt
> -    if (false !== strpos($json, 'consumer_lag":9')) {
On `librdkafka` `1.0.0` consumer_lag property was never different than `-1` or `0` for me.

2019-05-10 01:47 UTC, Steveb-p commented on tests/message_headers.phpt
> -EOF
This test also indicated memory leaks when `--enable-debug` php build was used.

```
5 messages delivered
Got message: message 0 | Headers: key: value
Got message: message 1 | Headers: key1: value1, key2: value2, key3: value3
Got message: message 2 | Headers: none
Got message: message 3 | Headers: none
Got message: message 4 | Headers: none
[Fri May 10 03:29:22 2019]  Script:  '/home/steveb/CLionProjects/php-rdkafka/tests/message_headers.php'
/home/steveb/CLionProjects/php-src/Zend/zend_string.h(133) :  Freeing 0x00007fce02464e00 (32 bytes), script=/home/steveb/CLionProjects/php-rdkafka/tests/message_headers.php
Last leak repeated 7 times
[Fri May 10 03:29:22 2019]  Script:  '/home/steveb/CLionProjects/php-rdkafka/tests/message_headers.php'
/home/steveb/CLionProjects/php-src/Zend/zend_string.h(133) :  Freeing 0x00007fce02464e40 (32 bytes), script=/home/steveb/CLionProjects/php-rdkafka/tests/message_headers.php
Last leak repeated 7 times
[Fri May 10 03:29:22 2019]  Script:  '/home/steveb/CLionProjects/php-rdkafka/tests/message_headers.php'
/home/steveb/CLionProjects/php-src/Zend/zend_hash.c(224) :  Freeing 0x00007fce02465c60 (56 bytes), script=/home/steveb/CLionProjects/php-rdkafka/tests/message_headers.php
Last leak repeated 6 times
[Fri May 10 03:29:22 2019]  Script:  '/home/steveb/CLionProjects/php-rdkafka/tests/message_headers.php'
/home/steveb/CLionProjects/php-src/Zend/zend_hash.c(132) :  Freeing 0x00007fce02470080 (320 bytes), script=/home/steveb/CLionProjects/php-rdkafka/tests/message_headers.php
Last leak repeated 3 times
=== Total 27 memory leaks detected ===
```

2019-11-04 22:26 UTC, Steveb-p commented
@nick-zh I've rebased the branch and ran tests again - there is particularly one test failing: `tests/conf_callbacks_integration.phpt`. It throws `Exception` with code -185, which gets us `Local: Timed Out` after calling `$msg->errstr()`.

I've added Dockerfile with build and docker-compose.yaml to allow us to test locally in the same environment. I'll remove them once we're ok with results.

I'm running tests using `docker-compose run --rm php make test`.

2019-11-08 10:59 UTC, Steveb-p commented
We discussed this with @nick-zh in conversation.

Currently all tests integration tests are green apart from the one with statistic callback enabled - this one causes local librdkafka error (`-185`, which translated to `Local: Timed Out` on librdkafka > 1.0.0). This does not prevent user from properly reading statistic information or producing/consuming messages, but may indicate a problem somewhere.

I'll be working on introducing integration tests into Travis pipeline, so they will be executed as well.

2019-11-15 16:34 UTC, Steveb-p commented
Updated the PR with changes to CI pipeline:

- Split build and test parts of travis script
- Moved both building & testing into docker containers. At first I tried running Kafka/Zookeeper containers and run into an issue with one of the tests failing. Tried the same in containers and it passed. However, after a couple more run it became apparent that the test is unstable and passes in roughly 50% of cases, so my initial assumption that host -> docker connectivity was at fault was wrong. I can revert to testing from Travis host environment.
- Tests now use primarily use environment variables to decide if integration tests should run. You can still use test_env.php file, but I'd say we should eventually drop it?
- Added librdkafka 1.2.2 to build matrix and made librdkafka repository configurable if needed (with sensible defaults)

I've decided to limit test matrix temporarily to just one job to speed up the process of adjusting tests, and will re-enable others once we're happy with them.

Thoughts @arnaud-lb @nick-zh? What can be the cause of this single test failing? There are other Consumer tests before it and they're not affected by described instability.

2019-11-19 07:39 UTC, nick-zh commented
@Steveb-p i will have a look over the weekend, sry ultra busy this week, so i probably won't find time earlier

2019-12-01 08:06 UTC, nick-zh requested changes
i did a review of the docker setup and left some notes,
i will be checking the actuall test changes later today :v:

2019-12-01 08:06 UTC, nick-zh commented on .travis.yml
> -    - nightly
would be nice to still have nightly

2019-12-01 08:06 UTC, nick-zh commented on Dockerfile
> +    $PHPIZE_DEPS \
maybe i overlooked it, but i was unalbe to finde the definition of `$PHPIZE_DEPS`

2019-12-01 08:06 UTC, nick-zh commented on .travis.yml
> +        - LIBRDKAFKA_VERSION=0.11.x PHP_IMAGE_VERSION=5.6
```suggestion
        - LIBRDKAFKA_VERSION=0.11.x PHP_IMAGE_VERSION=5.6-alpine
```
i think it would be nice to actually use the alpine images, since they are about a 5th of the debian images

2019-12-01 08:06 UTC, nick-zh commented on docker-compose.yaml
> +      context: .
```suggestion
      context: .
      args:
        LIBRDKAFKA_VERSION: ${LIBRDKAFKA_VERSION}
        PHP_IMAGE_VERSION: ${PHP_IMAGE_VERSION}
```

2019-12-01 08:06 UTC, nick-zh commented on .travis.yml
> +    - docker-compose run --rm php
intstead of the three commands you have now, i would probably just do a:
```
docker-compose up --build -d
```
with the changes in `docker-compose.yml` we shouldn't be needing the build args here.
If we see we have a timing issue, we can add a little loop here (or in a script) which waits for kafka to be available on its port. I think starting it like this, might still not guarantee that you don't run into timing issues.

2019-12-01 08:06 UTC, nick-zh commented on Dockerfile
> +ARG LIBRDKAFKA_VERSION='v1.2.1'
```suggestion
ARG LIBRDKAFKA_VERSION='v1.2.2'
```

2019-12-01 08:06 UTC, nick-zh commented on docker-compose.yaml
> +      - ./tests:/build/tests
since we copy the whole source into the container, do you think this is still needed?

2019-12-01 08:06 UTC, nick-zh commented on CONTRIBUTING.md
> +docker-compose run --rm php
if we change the script for travis, adjust here accordingly as well ofc 
very nice addition, i like it very much :heart:

2019-12-01 08:06 UTC, nick-zh commented on Dockerfile
> +    && apt-get update \
when switching to alpine, to install stuff, you can simply use:
```
apk add $PHPIZE_DEPS bash git valgrind
```
i think the source extract is not needed (at least i don't rembember using it for alpine)

2019-12-01 08:06 UTC, nick-zh commented on tests/allow_null_payload_and_key.phpt
> +if (getenv('TEST_KAFKA_BROKERS') === false) {
instead of changing this, what i would do is, i would add another file `tests/test_env.php.template`
with the following content:
```
define('TEST_KAFKA_BROKERS', ${TEST_KAFKA_BROKERS});
define('TEST_KAFKA_BROKER_VERSION', ${TEST_KAFKA_BROKER_VERSION});
```
make sure that we have those envs during the build of our docker image.
Make sure you have also installed `gettext` (alpine).
Then what you can do is after you have copied the source in the docker image:
``` 
RUN envsubst < "tests/test_env.php.template" > "tests/test_env.php"
```
with this, we can probably even get rid of the file_exists check

2019-12-01 13:03 UTC, Steveb-p commented on docker-compose.yaml
> +      - ./tests:/build/tests
I used it to get test results back to host filesystem. Since .phpt's usually don't output useful information (or at least I'm not familiar with those types of tests to set them up properly) I used it to look over expected/actual/diff.

2019-12-01 22:18 UTC, Steveb-p commented on .travis.yml
> -    - nightly
I'm going to revert changes to travis CI in this regard. Building PHP in "main travis thread" should be sufficient, and I only wanted to use Kafka image to ease starting of it's service. 

The only reason I actually removed PHP from Travis was to check if those builds behave the same way in docker containers (with tests failing on particular occasions, which they do :disappointed: )

2019-12-01 22:21 UTC, Steveb-p commented on .travis.yml
> +        - LIBRDKAFKA_VERSION=0.11.x PHP_IMAGE_VERSION=5.6
I didn't want to use alpine, because in general use case users build phprdkafka in context of debian/ubuntu servers and I wanted to "test" relevant installation instructions this way.

IMO we could provide instructions how to build on alpine, if any steps differ from "normal" linux OS.

2019-12-02 00:09 UTC, Steveb-p commented on tests/allow_null_payload_and_key.phpt
> +if (getenv('TEST_KAFKA_BROKERS') === false) {
I've added `tests/integration-tests-check.php` that should do environment variables handling/check and should be loaded before each integration test. I've also switched from using constants to environment variables everywhere.

2019-12-02 00:10 UTC, Steveb-p commented on Dockerfile
> +    && apt-get update \
I'm not sure but I think that without php sources valgrind will report false positives in memory leaks? But I'm not sure, I was having issues with valgrind anyway :confused:

2019-12-02 00:11 UTC, Steveb-p commented on CONTRIBUTING.md
> +docker-compose run --rm php
While I like it as well, as I said, there are some caveats that occur with docker-based Kafka :confused: Until they are sorted they will cause tests to fail in such environment.

2019-12-02 00:11 UTC, Steveb-p commented on docker-compose.yaml
> +      context: .
Adjusted accordingly.

2019-12-02 00:15 UTC, Steveb-p commented
I've managed to get those integration tests to work (finally). 

I had to scrap docker completely as it seems that there are some issues stemming from it. I've went back to keeping everything in host OS and I have found that **we have probably broke the `producev` method** at `ed6c5e9837cbcaac873b31701335edcf00590bbe`. I've rebased the branch just before that commit and all integration tests pass. As soon as those changes are added, calling `producev` results in early termination by `SIGTERM` signal.

2019-12-02 05:22 UTC, nick-zh commented
@Steveb-p ok, good to know, i am assuming you will revert the travis / docker changes then? I think i will have a look at a later point to add docker test support.
About the sigterm, i will have a look, i think i tested the use of producev, but i will have another look.
If there is some additional trace / log you could provide, that would be also great.

2019-12-02 08:45 UTC, Steveb-p commented
> ok, good to know, i am assuming you will revert the travis / docker changes then?
Already done that, only left `Dockerfile` and `docker-compose.yaml` atm. `.travis.yaml` has been changed to work with host OS again only.

> About the sigterm, i will have a look, i think i tested the use of producev, but i will have another look.
> If there is some additional trace / log you could provide, that would be also great.
I'm assuming you've got that yourself since you've got #318. I've cherry-picked the commit and we'll see how the tests go.

2019-12-04 06:45 UTC, nick-zh requested changes

2019-12-04 06:45 UTC, nick-zh commented on tests/bug115.phpt
> +    if (!$msg) {
```suggestion
    if (null === $msg || $msg->err === RD_KAFKA_RESP_ERR__PARTITION_EOF) {
```

2019-12-04 06:45 UTC, nick-zh commented on tests/produce_consume.phpt
>      if (!$msg) {
```suggestion
    // EOF reached
    if (null === $msg || $msg->err === RD_KAFKA_RESP_ERR__PARTITION_EOF) {
```
This way we have it in one place and can remove the switch below, for me it would be less confusing if i was new to this

2019-12-04 06:45 UTC, nick-zh commented on tests/produce_consume_queue.phpt
>      if (!$msg) {
same here with the eof as above :smiley:

2019-12-04 06:45 UTC, nick-zh commented on tests/produce_consume_queue.phpt
>  $eof = 0;
if this count is obsolete, can also be removed here

2019-12-04 06:45 UTC, nick-zh commented on tests/integration-tests-check.php
> +<?php
i would actually remove this file and put the checks back as they were and just do the adjustments in the sample

2019-12-04 06:45 UTC, nick-zh commented on tests/bug115.phpt
> +    $conf->set('broker.version.fallback', getenv('TEST_KAFKA_BROKER_VERSION'));
I actually think we can get rid of the version everywhere, the default should works for us and we are not using multiple versions of Kafka.

2019-12-04 06:45 UTC, nick-zh commented on tests/test_env.php.sample
> +putenv('TEST_KAFKA_BROKER_VERSION=2.3');
```suggestion
```

2019-12-04 06:45 UTC, nick-zh commented on tests/test_env.php.sample
> +putenv('TEST_KAFKA_BROKERS=localhost:9092');
```suggestion
if(false === getenv('TEST_KAFKA_BROKERS')) {
    putenv('TEST_KAFKA_BROKERS=localhost:9092');
}
```

2019-12-04 06:45 UTC, nick-zh commented on .travis.yml
> +        - TEST_KAFKA_BROKER_VERSION=2.3
```suggestion
```

2019-12-04 06:45 UTC, nick-zh commented on .travis.yml
> +        - LIBRDKAFKA_VERSION=v1.2.2
```suggestion
```
don't think we need it as globabl, but not sure, let me know

2019-12-04 08:47 UTC, Steveb-p commented on tests/test_env.php.sample
> +putenv('TEST_KAFKA_BROKER_VERSION=2.3');
You want this environment variable to be removed?

2019-12-04 08:57 UTC, nick-zh commented on tests/bug115.phpt
> +    $conf->set('broker.version.fallback', getenv('TEST_KAFKA_BROKER_VERSION'));
nah i was wrong, i checked, the default was changed after `librdkafka:0.11.6` and since we still support that, we need it for now.

2019-12-04 09:34 UTC, Steveb-p commented on .travis.yml
> +        - LIBRDKAFKA_VERSION=v1.2.2
Travis behaves funny if it's missing (afair it doesn't apply matrix properly) and I've seen it in Doctrine ODM as well, so it's not "just us".

2019-12-04 16:54 UTC, Steveb-p commented on tests/integration-tests-check.php
> +<?php
I'm leaning towards leaving it to allow local testing. This ensures that you can use either environment variables or `test_env.php` file to allow integration tests - and you can opt-out if you want, if you're not running local kafka instance (not to mention the amount of time those tests take, which is far more than "unit" ones).

2019-12-04 16:54 UTC, Steveb-p commented on .travis.yml
> +        - LIBRDKAFKA_VERSION=v1.2.2
see https://github.com/doctrine/mongodb-odm/blob/master/.travis.yml#L17

2019-12-04 16:57 UTC, Steveb-p commented
All commits squashed. I'd say it's as good as it's gonna get, and we can still work on this after it's merged (integration tests missing really hurt us with `producev` method :disappointed: ).

We can add more tests further on.

Care for re-review @nick-zh? Any comments @arnaud-lb?

2019-12-05 09:03 UTC, arnaud-lb commented
Great work @Steveb-p ! 

I see that you added a `Dockerfile` / `docker-compose.yml`, where is this used ?

Just a note on `RD_KAFKA_RESP_ERR__PARTITION_EOF`: Messages with this error code are returned only when `enable.partition.eof` is `true` in the conf.

2019-12-05 09:11 UTC, Steveb-p commented
> I see that you added a `Dockerfile` / `docker-compose.yml`, where is this used ?

It's a leftover from attempting to simplify local testing by providing an "automated" and consistent build and testing tool. I backed down from it since callback integration tests failed with a high rate, only to see them fail as well - albeit with roughly 50/50 change - on normal, host-based testing.

That's why this test is currently skipped, so integration tests can be enabled to prevent issues like the one with `producev` and we can work on introducing more test cases / organize them better.

All in all, I'll remove those files and put them back with instructions in a separate PR.

> Just a note on `RD_KAFKA_RESP_ERR__PARTITION_EOF`: Messages with this error code are returned only when `enable.partition.eof` is `true` in the conf.

Practically it's only checked for tests for librdkafka 0.11.6, since the defaults changed afaik? We can switch to setting `enable.partition.eof` always instead, but I didn't want to change tests too much.

2019-12-05 09:18 UTC, nick-zh commented
@Steveb-p `enable.partition.eof` is `true` for anything before `librdkafka:1.0.0`

2019-12-05 11:46 UTC, nick-zh requested changes

2019-12-05 11:46 UTC, nick-zh commented on tests/produce_consume_queue.phpt
>  }
```
while (true) {
    $msg = $queue->consume(15000);
    // librdkafka before 1.0 returns message with RD_KAFKA_RESP_ERR__PARTITION_EOF when reaching topic end.
    if (!$msg) {
        continue;
    }

    if ($msg->err === RD_KAFKA_RESP_ERR__PARTITION_EOF) {
        break;
    } elseif (RD_KAFKA_RESP_ERR_NO_ERROR !== $msg->err) {
        throw new Exception($msg->errstr(), $msg->err);
    }
    $messages[] = sprintf("Got message: %s from %s", $msg->payload, $msg->topic_name);
}
```

2019-12-05 11:46 UTC, nick-zh commented on tests/produce_consume_queue.phpt
>  $conf = new RdKafka\Conf();
```suggestion
$conf = new RdKafka\Conf();
$conf->set('enable.partition.eof', 'true');
```

2019-12-05 13:36 UTC, nick-zh commented
@arnaud-lb LGTM, please let us know if we need more, otherwise should be good to merge :tada: 
Thx a lot @Steveb-p , with docker in place, makes it a bit easier for me to run this locally :heart:

2019-12-05 13:36 UTC, nick-zh approved these changes

2019-12-06 08:47 UTC, merged

2019-12-06 08:47 UTC, arnaud-lb commented
Thanks @Steveb-p !