Expand readme for configuration parameters
php-rdkafka/php-rdkafka pull request #307
Opened 2019-11-04 09:35 UTC by Steveb-p

See https://github.com/arnaud-lb/php-rdkafka/issues/305#issuecomment-547322127

2019-11-04 09:52 UTC, nick-zh requested changes

2019-11-04 09:52 UTC, nick-zh commented on README.md
> +Adding topics to the queue:
```suggestion
Adding topic partitions to the queue:
```

2019-11-04 09:52 UTC, nick-zh commented on README.md
> +librdkafka can store offsets in a local file, or on the broker.
```suggestion
#### Broker (default)
librdkafka per default stores offsets on the broker.
```

2019-11-04 09:52 UTC, nick-zh commented on README.md
> +For older versions of librdkafka library, default value was storing offset values in local file, but it has since been
```suggestion
#### File offsets (deprecated)
```
we probably shouldn't give guidance for a deprecated feature (imho)

2019-11-04 09:52 UTC, nick-zh commented on README.md
> +deprecated. Currently by default librdkafka will use broker as offset storage. You can switch it back by using
```suggestion
```

2019-11-04 09:52 UTC, nick-zh commented on README.md
> +`offset.store.method` configuration property.
```suggestion
```

2019-11-04 09:52 UTC, nick-zh commented on README.md
>  Other interesting properties are: ``auto.commit.interval.ms``, ``auto.commit.enable``, ``group.id``, ``max.poll.interval.ms``.
```suggestion
#### Useful offset settings
Other interesting properties are: ``auto.commit.interval.ms``, ``auto.commit.enable``, ``group.id``, ``max.poll.interval.ms``.
```

2019-11-04 09:52 UTC, nick-zh commented on README.md
> +https://arnaud-lb.github.io/php-rdkafka/phpdoc/book.rdkafka.html
```suggestion
https://arnaud-lb.github.io/php-rdkafka/phpdoc/book.rdkafka.html  
```

2019-11-04 10:14 UTC, nick-zh requested changes

2019-11-04 10:14 UTC, nick-zh commented on README.md
> +then you want to disable `auto.commit.enable`.
```suggestion
then you want to set `auto.commit.enable=false`.
```

2019-11-04 10:16 UTC, nick-zh requested changes

2019-11-04 10:16 UTC, nick-zh commented on README.md
> +`group.id` is responsible for setting your consumer group ID and it should be unique for your application (and should
```suggestion
`group.id` is responsible for setting your consumer group ID and it should be unique (and should
```

2019-11-04 20:37 UTC, Steveb-p commented on README.md
> +then you want to disable `auto.commit.enable`.
Replaced with
```md
to set `auto.commit.enable` to `'false'`
```
which should be even more accurate I believe?

2019-11-04 20:38 UTC, Steveb-p commented on README.md
> +`group.id` is responsible for setting your consumer group ID and it should be unique for your application (and should
Removed accordingly.

2019-11-18 07:12 UTC, nick-zh approved these changes

2019-11-18 07:13 UTC, nick-zh commented
Thanks @Steveb-p

2019-11-18 07:13 UTC, merged